% consejo_revisor(departamento, revisor)
consejo_revisor('Fisica', 'Newton').
consejo_revisor('Fisica', 'Galileo').
consejo_revisor('Fisica', 'Einstein').
consejo_revisor('Matematica', 'Gauss').
consejo_revisor('Matematica', 'Euler').
consejo_revisor('Matematica', 'Riemann').
consejo_revisor('Quimica', 'Lavoisier').
consejo_revisor('Quimica', 'Mendeleev').
consejo_revisor('Quimica', 'Curie').
consejo_revisor('Computacion', 'Turing').
consejo_revisor('Computacion', 'Von Neumann').
consejo_revisor('Computacion', 'Knuth').
consejo_revisor('Biologia', 'Darwin').
consejo_revisor('Biologia', 'Mendel').
consejo_revisor('Biologia', 'Watson').
consejo_revisor('Filosofia', 'Aristoteles').
consejo_revisor('Filosofia', 'Kant').
consejo_revisor('Filosofia', 'Hume').
consejo_revisor('Historia', 'Herodoto').
consejo_revisor('Historia', 'Tucidides').
consejo_revisor('Historia', 'Gibbon').
consejo_revisor('Economia', 'Smith').
consejo_revisor('Economia', 'Ricardo').
consejo_revisor('Economia', 'Keynes').
consejo_revisor('Medicina', 'Hipocrates').
consejo_revisor('Medicina', 'Galeno').
consejo_revisor('Medicina', 'Fleming').
consejo_revisor('Astronomia', 'Galileo').
consejo_revisor('Astronomia', 'Kepler').
consejo_revisor('Astronomia', 'Hubble').
consejo_revisor('Geografia', 'Ptolomeo').
consejo_revisor('Geografia', 'Mercator').
consejo_revisor('Geografia', 'Humboldt').
consejo_revisor('Psicologia', 'Freud').
consejo_revisor('Psicologia', 'Skinner').
consejo_revisor('Psicologia', 'Piaget').
consejo_revisor('Sociologia', 'Durkheim').
consejo_revisor('Sociologia', 'Weber').
consejo_revisor('Sociologia', 'Parsons').