% palabra_clave(nombre_departamento, palabra_clave)
palabra_clave('Fisica', 'Dinamica').
palabra_clave('Fisica', 'Optica').
palabra_clave('Fisica', 'Mecanica').
palabra_clave('Matematica', 'algebra').
palabra_clave('Matematica', 'Geometria').
palabra_clave('Matematica', 'Calculo').
palabra_clave('Quimica', 'Organica').
palabra_clave('Quimica', 'Inorganica').
palabra_clave('Quimica', 'Quimica').
palabra_clave('Computacion', 'Algoritmos').
palabra_clave('Computacion', 'Complejidad').
palabra_clave('Computacion', 'Programacion').
palabra_clave('Biologia', 'Genética').
palabra_clave('Biologia', 'Evolucion').
palabra_clave('Biologia', 'Ecologia').
palabra_clave('Filosofia', 'Ética').
palabra_clave('Filosofia', 'Estética').
palabra_clave('Filosofia', 'Logica').
palabra_clave('Historia', 'Antigua').
palabra_clave('Historia', 'Moderna').
palabra_clave('Historia', 'Contemporanea').
palabra_clave('Economia', 'Microeconomia').
palabra_clave('Economia', 'Macroeconomia').
palabra_clave('Economia', 'Finanzas').
palabra_clave('Medicina', 'Anatomia').
palabra_clave('Medicina', 'Fisiologia').
palabra_clave('Medicina', 'Patologia').
palabra_clave('Astronomia', 'Astrofisica').
palabra_clave('Astronomia', 'Cosmologia').
palabra_clave('Astronomia', 'Astrometria').
palabra_clave('Geografia', 'Fisica').
palabra_clave('Geografia', 'Humana').
palabra_clave('Geografia', 'Politica').
palabra_clave('Psicologia', 'Cognitiva').
palabra_clave('Psicologia', 'Social').
palabra_clave('Psicologia', 'Clinica').
palabra_clave('Sociologia', 'Cambio').
palabra_clave('Sociologia', 'Desigualdad').
palabra_clave('Sociologia', 'Educacion').